server:
  port: 8081
#????mybatis???
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:config/sqlMapConfig.xml
  type-aliases-package: com.kasi.firstdemo.entity
#?????
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
#??????????
logging:
  level:
    root: info
user:
  name: kasi
  address: ¶«Ý¸