server:
  port: 8085
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:config/sqlMapConfig.xml
  type-aliases-package: com.kasi.firstdemo.entity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
logging:
  level:
    root: info
user:
  name: kasi
  address: dongbao
api:
  appId: 11401830
  apiKey: yZaxmFtIgTLONfuwnSlZ0ad9
  secretKey: jSG8goj6FOGnfiTZrlxtUu8s7CN3QSjW
redis:
  hostName: 127.0.0.1
  port: 6379
  timeout: 10000
info:
  message: test